version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: dbpassword
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: dbpassword
    restart: always

  drupal:
    image: dosstp/drupal
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: dbpassword
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./files:/var/www/html/sites/default/files
    restart: always