adsync.settings:
  type: conﬁg_object
  mapping:
    ad_server:
      type: string
      label: '網域主控站'
    ca_cert:
      type: string
      label: '根憑證檔案'
    ad_admin:
      type: string
      label: '網域管理員帳號'
    ad_password:
      type: string
      label: '網域管理員密碼'
    users_dn:
      type: string
      label: '使用者命名空間'
    enabled:
      type: boolean
      label: 'AD 連線測試完成'
