gevent.settings:
  type: conﬁg_object
  mapping:
    entity_type:
      type: string
      label: '行事曆事件內容類型'
    field_title:
      type: string
      label: '行事曆事件摘要欄位對應'
    field_memo:
      type: string
      label: '行事曆事件說明欄位對應'
    field_place:
      type: string
      label: '行事曆事件地點欄位對應'
    field_attendee:
      type: string
      label: '行事曆事件與會人員欄位對應'
    field_calendar_id:
      type: string
      label: '儲存 Google 行事曆 ID'
    field_event_id:
      type: string
      label: '儲存 Google 行事曆事件 ID'
    calendar_owner:
      type: string
      label: 'Google 行事曆擁有者帳號'
    calendar_taxonomy:
      type: boolean
      label: '透過分類系統對應不同 Google 行事曆'
    calendar_id:
      type: string
      label: '指定要對應的 Google 行事曆 ID'
    enabled:
      type: boolean
      label: 'Google Calendar API 測試完成'
