gevent.settings:
  type: conﬁg_object
  mapping:
    entity_type:
      type: string
      label: '行事曆事件內容類型'
    field_title:
      type: string
      label: 'G Suite 管理員帳號'
    field_memo:
      type: string
      label: 'G Suite 網域'
    field_place:
      type: string
      label: '教師帳號所在的 G Suite 子機構'
    field_attendee:
      type: string
      label: '學生帳號所在的 G Suite 子機構'
    field_calendar_id:
      type: string
      label: '學生帳號的樣式'
    field_event_id:
      type: string
      label: '學生帳號的樣式'
    calendar_owner:
      type: string
      label: '學生帳號的樣式'
    enabled:
      type: boolean
      label: 'Google API 測試完成'
