google_login:
  type: boolean
  label: '啟用 G Suite 帳號登入'
google_oauth_json:
  type: string
  label: 'Google Oauth 用戶端授權驗證檔案'
google_call_back:
  type: string
  label: 'Google 授權後轉送網址'
google_domain_admin:
  type: boolean
  label: '啟用 G Suite 帳號同步'
google_service_json:
  type: string
  label: 'Google Service Account 授權檔案'