enable:
  type: boolean
  label: '已啟用臺北市教育人員單一身分驗證模組'
client_id:
  type: string
  label: '臺北市教育人員單一身分驗證介接專案編號'
client_secret:
  type: string
  label: '臺北市教育人員單一身分驗證介接專案密鑰'
admin_token:
  type: string
  label: '臺北市教育人員單一身分驗證學校管理員預存令牌'
allow_default_login:
  type: boolean
  label: '允許使用 Drupal 本地帳號登入'
login_goto_url:
  type: string
  label: '（選項）使用者登入後要轉送到哪個 URL'
logout_goto_url:
  type: string
  label: '（選項）使用者登出後要轉送到哪個 URL'
personal_data_notice:
  type: boolean
  label: '要顯示個資政策連結嗎？'
